// <auto-generated />
using System;
using ElTrueque.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Feriando.DataAccess.Migrations
{
    [DbContext(typeof(ElTruequeDbContext))]
    [Migration("20261003074549_AgregarMensajesChat")]
    partial class AgregarMensajesChat
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ElTrueque.Api.Models.Categoria", b =>
                {
                    b.Property<int>("CategoriaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriaID"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Icono")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoriaID");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("ElTrueque.Api.Models.Departamento", b =>
                {
                    b.Property<int>("DepartamentoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartamentoID"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("DepartamentoID");

                    b.ToTable("Departamentos");
                });

            modelBuilder.Entity("ElTrueque.Api.Models.Idioma", b =>
                {
                    b.Property<int>("IdiomaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdiomaID"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("IdiomaID");

                    b.ToTable("Idiomas");
                });

            modelBuilder.Entity("ElTrueque.Api.Models.ImagenProducto", b =>
                {
                    b.Property<int>("ImagenID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImagenID"));

                    b.Property<byte>("Orden")
                        .HasColumnType("tinyint");

                    b.Property<int>("ProductoID")
                        .HasColumnType("int");

                    b.Property<string>("UrlImagen")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("ImagenID");

                    b.HasIndex("ProductoID");

                    b.ToTable("ImagenesProducto");
                });

            modelBuilder.Entity("ElTrueque.Api.Models.MensajeChat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChatId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmisorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaEnvio")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Leido")
                        .HasColumnType("bit");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MensajesChat");
                });

            modelBuilder.Entity("ElTrueque.Api.Models.Municipio", b =>
                {
                    b.Property<int>("MunicipioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MunicipioID"));

                    b.Property<int>("DepartamentoID")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MunicipioID");

                    b.HasIndex("DepartamentoID");

                    b.ToTable("Municipios");
                });

            modelBuilder.Entity("ElTrueque.Api.Models.Notificacion", b =>
                {
                    b.Property<int>("NotificacionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificacionID"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Leido")
                        .HasColumnType("bit");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("TruequeID")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.HasKey("NotificacionID");

                    b.HasIndex("TruequeID");

                    b.HasIndex("UsuarioID");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("ElTrueque.Api.Models.Producto", b =>
                {
                    b.Property<int>("ProductoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductoID"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("CategoriaID")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Disponible");

                    b.Property<DateTime>("FechaPublicacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal?>("PrecioReferencial")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("TipoOferta")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UnidadMedidaID")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.HasKey("ProductoID");

                    b.HasIndex("CategoriaID");

                    b.HasIndex("UnidadMedidaID");

                    b.HasIndex("UsuarioID");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("ElTrueque.Api.Models.Trueque", b =>
                {
                    b.Property<int>("TruequeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TruequeID"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pendiente");

                    b.Property<DateTime?>("FechaCompletado")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaRespuesta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("datetime2");

                    b.Property<string>("LugarEncuentro")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("MontoAdicional")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ProductoOfertadoID")
                        .HasColumnType("int");

                    b.Property<int?>("ProductoSolicitadoID")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioReceptorID")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioSolicitanteID")
                        .HasColumnType("int");

                    b.HasKey("TruequeID");

                    b.HasIndex("ProductoOfertadoID");

                    b.HasIndex("ProductoSolicitadoID");

                    b.HasIndex("UsuarioReceptorID");

                    b.HasIndex("UsuarioSolicitanteID");

                    b.ToTable("Trueques");
                });

            modelBuilder.Entity("ElTrueque.Api.Models.UnidadMedida", b =>
                {
                    b.Property<int>("UnidadMedidaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UnidadMedidaID"));

                    b.Property<string>("Abreviatura")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("UnidadMedidaID");

                    b.ToTable("UnidadesMedida");
                });

            modelBuilder.Entity("ElTrueque.Api.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioID"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Correo")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("DireccionExacta")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("EsProductora")
                        .HasColumnType("bit");

                    b.Property<bool>("EstadoActivo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("FotoPerfil")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Genero")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<int?>("IdiomaPreferidoID")
                        .HasColumnType("int");

                    b.Property<int>("MunicipioID")
                        .HasColumnType("int");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("UsuarioID");

                    b.HasIndex("Correo")
                        .IsUnique()
                        .HasFilter("[Correo] IS NOT NULL");

                    b.HasIndex("IdiomaPreferidoID");

                    b.HasIndex("MunicipioID");

                    b.HasIndex("Telefono")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ElTrueque.Api.Models.Valoracion", b =>
                {
                    b.Property<int>("ValoracionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ValoracionID"));

                    b.Property<string>("Comentario")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("FechaValoracion")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Puntuacion")
                        .HasColumnType("tinyint");

                    b.Property<int>("TruequeID")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioEvaluadoID")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioEvaluadorID")
                        .HasColumnType("int");

                    b.HasKey("ValoracionID");

                    b.HasIndex("TruequeID");

                    b.HasIndex("UsuarioEvaluadoID");

                    b.HasIndex("UsuarioEvaluadorID");

                    b.ToTable("Valoraciones");
                });

            modelBuilder.Entity("ElTrueque.Api.Models.ImagenProducto", b =>
                {
                    b.HasOne("ElTrueque.Api.Models.Producto", "Producto")
                        .WithMany("Imagenes")
                        .HasForeignKey("ProductoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("ElTrueque.Api.Models.Municipio", b =>
                {
                    b.HasOne("ElTrueque.Api.Models.Departamento", "Departamento")
                        .WithMany("Municipios")
                        .HasForeignKey("DepartamentoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("ElTrueque.Api.Models.Notificacion", b =>
                {
                    b.HasOne("ElTrueque.Api.Models.Trueque", "Trueque")
                        .WithMany()
                        .HasForeignKey("TruequeID");

                    b.HasOne("ElTrueque.Api.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trueque");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ElTrueque.Api.Models.Producto", b =>
                {
                    b.HasOne("ElTrueque.Api.Models.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElTrueque.Api.Models.UnidadMedida", "UnidadMedida")
                        .WithMany()
                        .HasForeignKey("UnidadMedidaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElTrueque.Api.Models.Usuario", "Usuario")
                        .WithMany("Productos")
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("UnidadMedida");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ElTrueque.Api.Models.Trueque", b =>
                {
                    b.HasOne("ElTrueque.Api.Models.Producto", "ProductoOfertado")
                        .WithMany()
                        .HasForeignKey("ProductoOfertadoID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ElTrueque.Api.Models.Producto", "ProductoSolicitado")
                        .WithMany()
                        .HasForeignKey("ProductoSolicitadoID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ElTrueque.Api.Models.Usuario", "UsuarioReceptor")
                        .WithMany()
                        .HasForeignKey("UsuarioReceptorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ElTrueque.Api.Models.Usuario", "UsuarioSolicitante")
                        .WithMany()
                        .HasForeignKey("UsuarioSolicitanteID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductoOfertado");

                    b.Navigation("ProductoSolicitado");

                    b.Navigation("UsuarioReceptor");

                    b.Navigation("UsuarioSolicitante");
                });

            modelBuilder.Entity("ElTrueque.Api.Models.Usuario", b =>
                {
                    b.HasOne("ElTrueque.Api.Models.Idioma", "IdiomaPreferido")
                        .WithMany()
                        .HasForeignKey("IdiomaPreferidoID");

                    b.HasOne("ElTrueque.Api.Models.Municipio", "Municipio")
                        .WithMany("Usuarios")
                        .HasForeignKey("MunicipioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdiomaPreferido");

                    b.Navigation("Municipio");
                });

            modelBuilder.Entity("ElTrueque.Api.Models.Valoracion", b =>
                {
                    b.HasOne("ElTrueque.Api.Models.Trueque", "Trueque")
                        .WithMany("Valoraciones")
                        .HasForeignKey("TruequeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElTrueque.Api.Models.Usuario", "UsuarioEvaluado")
                        .WithMany()
                        .HasForeignKey("UsuarioEvaluadoID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ElTrueque.Api.Models.Usuario", "UsuarioEvaluador")
                        .WithMany()
                        .HasForeignKey("UsuarioEvaluadorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Trueque");

                    b.Navigation("UsuarioEvaluado");

                    b.Navigation("UsuarioEvaluador");
                });

            modelBuilder.Entity("ElTrueque.Api.Models.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("ElTrueque.Api.Models.Departamento", b =>
                {
                    b.Navigation("Municipios");
                });

            modelBuilder.Entity("ElTrueque.Api.Models.Municipio", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("ElTrueque.Api.Models.Producto", b =>
                {
                    b.Navigation("Imagenes");
                });

            modelBuilder.Entity("ElTrueque.Api.Models.Trueque", b =>
                {
                    b.Navigation("Valoraciones");
                });

            modelBuilder.Entity("ElTrueque.Api.Models.Usuario", b =>
                {
                    b.Navigation("Productos");
                });
#pragma warning restore 612, 618
        }
    }
}
